### ISSUE TITLE
Incorrect assertion: `git add <file>`

### ISSUE THREAD

**Issue by dkjain** [shvetsgroup/githowto-content#14]
on Githowto.com you say, "A git add file command does not tell git to add the file to the repository, but to note the current state of the file for it to be commited later." [URL](https://githowto.com/changes_not_files).

In the video from Michael Schwern [git for ages 4 and Up](https://www.youtube.com/watch?v=3m7BgIvC-uQ), (~09:30s) he specifically says that `git add <file>` adds/writes to the repo and commit actually turns it into a commit object however what you say on your website is completely the opposite. I am not sure, who is correct here? Can you plz comment.

**Comment by neochief** [comment]
I don't think that these two thoughts contradict each other.

`git add <file>` adds/writes to the repo **/a note the current state of the file for it to be committed later/** and commit actually turns it into a commit object
