### ISSUE TITLE
In Russian translation, I suggest to use or 'Otdalenniy' instead of 'Udalenniy'.

### ISSUE THREAD

**Issue by teterkin** [shvetsgroup/githowto-content#18]
I suggest to use 'Otdalenniy' instead of 'Udalenniy'.

Example:
```
--- Мы видим, что «имя по умолчанию» удаленного репозитория – оригинальное hello. 
+++ Мы видим, что «имя по умолчанию» отдаленного репозитория – оригинальное hello. 
```
**Link to Cambridge Dictionary**
[http://dictionary.cambridge.org/ru/словарь/англо-русский/remote](http://dictionary.cambridge.org/ru/%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C/%D0%B0%D0%BD%D0%B3%D0%BB%D0%BE-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9/remote)

Применительно к географическим объектам мы обычно говорим: "Отдалённая деревенька", "Места не столь отдаленные" и т.п. "Отдалённый репозиторий" звучит конечно старанно всё равно, но лучше чем "удалённый репозиторий".

Как вы думаете?

**Comment by neochief** [comment]
Понимаю мотивацию к такой замене. Но «отдалённый» тоже звучит странновато, хотя может просто непривычно. Просто если взять ту же винду, в ней «remote access» это «удалённый доступ». Вроде все уже привыкли.

**Comment by teterkin** [comment]
Согласен, что привыкли. 
I agree that we all got used to wrong translation. 
As you said "Microsoft remote desktop" is always translated as "Udalenniy Rabochiy Stol".
I just have looked at [http://www.multitran.ru/c/m.exe?CL=1&s=remote&l1=1](http://www.multitran.ru/c/m.exe?CL=1&s=remote&l1=1). 
Seems like most of people use "Udalenny" word.
Ok. I will close the issue. 
Thank you for the answer!
