### ISSUE TITLE
Typo in russian version of chapter 10 "History"

### ISSUE THREAD

**Issue by ptaiga** [shvetsgroup/githowto-content#19]
Author is a man, but in [https://githowto.com/ru/history](https://githowto.com/ru/history) text sometimes is feminine.

I found the following typo:

1. _"если я хочу увидеть только изменения, которые сделалА я"_
2. _"Со временем, я решилА"_

Of course, it's not critical, but catches the eye :)

**Comment by neochief** [comment]
Fixed, thanks!
