### ISSUE TITLE
Examples does not work with github

### ISSUE THREAD

**Issue by roman4e** [shvetsgroup/githowto-content#5]
$ git clone https://...git
change something
$ git commit -m "Message"
> Your branch is up-to-date with 'origin/master'. 
> Changes not staged for commit

-- WHAT?
so you can't

$ git push
> Everything up-to-date

**Comment by Soreine** [comment]
It looks like you forgot to stage your changes, as git says "Changes not staged for commit". The standard process is as follow:

```
$ git clone https://...git
```
Change `file.txt`

```
$ git add file.txt
$ git commit -m "Message"
$ git push
```
The `git add` command stages a change so it is included in the next commit. 

At any moment, you can check which changes are staged and which are not with the `git status` command. This would be the output of the `git status` command, if executed after making a change to `file.txt`:

```
$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   file.txt

no changes added to commit (use "git add" and/or "git commit -a")
```
 You can see that `git status` also suggests how one would add changes to a commit.

**Comment by roman4e** [comment]
Oh. That's solution. thanks a lot
